$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file and which type they should be
properties:
    sample:
        type: string
        description: sample name/identifier
    technology:
        type: string
        description: sequencing technology (nanopore or pacbio)
        pattern: "^(pacbio)|(nanopore)$"
    nstrains:
        type: number
        description: strainberry's strain multiplicity

# entries that have to be in the config file for successful validation
required:
  - sample
  - technology
  - nstrains
